### ISSUE TITLE
masterRelation not working for Umbraco 7 MNTP / contentpickers

### ISSUE THREAD

**Issue by rodyvansambeek** [TeaCommerce/Tea-Commerce-for-Umbraco#63] opened 2018-02-23 14:22 UTC
When using the (not obsolete) MNTP or contentpickers from Umbraco the masterRelation functionality does not work. Because the code in the ProductInformationExtractor thinks he will receive a NodeId, where instead in the new pickers it receives on IPublishedContent.

**Comment by arknu** [comment] 2019-02-14 13:20
This is a pretty huge issue with a really, really simple fix. The problem is this line: https://github.com/TeaCommerce/Tea-Commerce-for-Umbraco/blob/4e6cf88bcd6234f2a45e868aee890b1fb4fca603/Source/TeaCommerce.Umbraco.Configuration/InformationExtractors/PublishedContentProductInformationExtractor.cs#L238 where it expects a string return value. This should be changed to IEnumerable<IPublishedContent>, with a fallback to string.

Might do a PR this weekend if I have time.

**Comment by mattbrailsford** [comment] 2019-02-14 13:26
@arknu that would be awesome if you could 👍

**Comment by arknu** [comment] 2019-02-14 13:47
@mattbrailsford Well, no time like the present :) Decided to do the PR right now: https://github.com/TeaCommerce/Tea-Commerce-for-Umbraco/pull/77.

**Comment by mattbrailsford** [comment] 2019-02-14 13:55
Haha, that's awesome, thank you. Will review it shortly. 👏

**Comment by mattbrailsford** [comment] 2019-02-14 14:14
Fixed in merged PR #77. Will be in 3.3.1 release. Thank you @arknu

**Closed by mattbrailsford** 2019-02-14 14:14 UTC
