### ISSUE TITLE
Umbraco 7.2 bug with order search page

### ISSUE THREAD

**Issue by TomSteer** [TeaCommerce/Tea-Commerce-for-Umbraco#31] opened 2015-01-20 14:49 UTC
I've just tried upgrading a site to 7.2.1 and when I navigate to the Tea Commerce order search page in Umbraco I get the following error:

An error occurred during the compilation of a resource required to service this request. Please review the following specific error details and modify your source code appropriately. 

Compiler Error Message: CS0104: 'Constants' is an ambiguous reference between 'ClientDependency.Core.Constants' and 'TeaCommerce.Umbraco.Application.Constants'

Thanks,

Tom

**Comment by andersburla** [comment] 2015-02-04 14:37
What version of Tea Commerce do you use?

**Comment by tommyflint** [comment] 2015-02-04 14:49
I was using v3

**Comment by andersburla** [comment] 2015-02-04 14:51
Just installed 3.0 on 7.2.1 and it worked out of the box. Was your an update or?

**Comment by tommyflint** [comment] 2015-02-04 14:55
That's odd... It was an upgrade from 7.1.8 (I think) I'm assuming your test was before Richard's commit ;)

**Comment by andersburla** [comment] 2015-02-04 15:02
Yes - I can't reproduce it. So we will close it and hope Richards commit will fix the rare cases :)

**Closed by andersburla** 2015-02-04 15:02 UTC
Labels: bug
